version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docbuddy
    ports:
      - "3306:3306"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  
      